name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para atualizar tags corretamente

      - name: Ler valor da tag do arquivo
        id: read_tag
        run: |
          TAG=$(cat version)
          echo "tag_version=$TAG" >> $GITHUB_ENV

      - name: Criar tag no GitHub
        run: |
          git config user.name "${{ vars.USERNAME_GITHUB }}"
          git config user.email "${{ vars.EMAIL_GITHUB }}"
          git tag -f ${{ env.tag_version }}
          git push origin ${{ env.tag_version }} --force

  build-Go-App:
    runs-on: ubuntu-latest
    needs: update-tag  # ⬅️ Aguarda a execução do "update-tag"
    
    steps:
    - uses: actions/checkout@v4

    - name: Ler valor da tag do arquivo
      id: read_tag
      run: |
        TAG=$(cat version)
        echo "tag_version=$TAG" >> $GITHUB_ENV
    
    - name: Set up version
      run: echo "IMAGE_VERSION=${{ env.tag_version }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --tag ${{ vars.DOCKER_HUB_REPO }}:${IMAGE_VERSION}
        docker tag ${{ vars.DOCKER_HUB_REPO }}:${IMAGE_VERSION} ${{ vars.DOCKER_HUB_REPO }}:${IMAGE_VERSION}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ vars.DOCKER_HUB_USER }} --password-stdin

    - name: Push image to Docker Hub
      run: |
        docker push ${{ vars.DOCKER_HUB_REPO }}:${IMAGE_VERSION}