name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para atualizar tags corretamente

      - name: Ler valor da tag do arquivo
        id: read_tag
        run: |
          TAG=$(cat version)
          echo "tag_version=$TAG" >> $GITHUB_ENV

      - name: Criar tag no GitHub
        run: |
          git config user.name "${{ vars.USERNAME_GITHUB }}"
          git config user.email "${{ vars.EMAIL_GITHUB }}"
          git tag -f $TAG
          git push origin $TAG --force

  build-Go-App:
    runs-on: ubuntu-latest
    needs: update-tag  # ⬅️ Aguarda a execução do "update-tag"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up version
      run: echo "IMAGE_VERSION=$TAG" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --tag damascenod/webserver:${IMAGE_VERSION}
        docker tag damascenod/webserver:${IMAGE_VERSION}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u damascenod --password-stdin

    - name: Push image to Docker Hub
      run: |
        docker push damascenod/webserver:${IMAGE_VERSION}